default_prompt = '你作为家庭智能健康管家，需要解答用户问题，如果用户回复了症状，则针对用户症状进行问诊；当用户提到高血压的相关症状时，如果对话历史中没有血压信息，则提示用户测量血压，如果对话中问过血压信息，就不要再问了，如果对话历史里有血压信息，则针对用户高血压症状问诊；如果用户提到其他疾病症状则对用户症状进行问诊。如果模型回复饮食情况则对用户饮食进行热量、膳食结构评价。下面是对话内容：\n'

EXT_USRINFO_TRANSFER_INTENTCODE = 'transfor_qa'

intentCode_desc_map = {
    'food_rec':'饮食处方咨询',
    'food_nutri':'饮食营养',
    'nutri_known':'营养知识咨询',
    'food_eval':'饮食评价',
    'nutri_other':'营养其他',
    'drug':'用药咨询',
    'call_other':'呼叫其他',
    'med_health':'医疗健康',
    'sport_rec':'运动咨询',
    'cookbook':'菜谱',
    'musicX':'音乐播放',
    'weather':'天气查询',
    'call_doctor':'呼叫医师',
    'call_sportMaster':'呼叫运动师',
    'call_psychologist':'呼叫情志师',
    'call_dietista':'呼叫营养师',
    'call_health_manager':'呼叫健管师',
    'other':'日常对话',
    'websearch':'网络搜索',
    'KLLI3.captialInfo':'首都查询',
    'lottery':'彩票',
    'dream':'周公解梦',
    'AIUI.calc':'计算器',
    'LEIQIAO.cityOfPro':'国内城市查询',
    'ZUOMX.queryCapital':'省会查询',
    'translation':'翻译',
    'garbageClassifyPro':'垃圾分类',
    'carNumber':'尾号限行',
    'AIUI.unitConversion':'单位换算',
    'AIUI.forexPro':'汇率',
    'datetimePro':'时间日期',
    'AIUI.ocularGym':'眼保健操',
    'story':'故事',
    'AIUI.Bible':'圣经',
    'drama':'戏曲',
    'storyTelling':'评书',
    'AIUI.audioBook':'有声书',
    'news':'新闻',
    'BMI':'BMI',
    'open_web_daily_monitor':'功能页面',
    'calendar':'万年历',
    'joke':'笑话',
    'other': '日常对话'
}
