local:
  langchain: http://10.228.67.99:26924
  llm: http://10.39.91.251:50013
  llm_token: sk-laikang-aihealthmanager-local
  graph: http://10.4.164.240:26925
  # ai_backend: https://gate-qa.op.laikang.com/aihealthmanager-alg    # 算法后端环境变更, 暂用dev
  ai_backend: https://gate-dev.op.laikang.com/aihealthmanager-dev
  algo_rec: http://aimp-algo-psc-diet-v5.en.laikang.com
dev:
  langchain: http://10.228.67.99:26924
  llm: http://localhost:50013
  llm_token: sk-laikang-aihealthmanager-dev
  graph: http://10.4.164.240:26925
  # ai_backend: https://gate-qa.op.laikang.com/aihealthmanager-alg    # 算法后端环境变更, 暂用dev
  ai_backend: https://gate-dev.op.laikang.com/aihealthmanager-dev
  algo_rec: http://aimp-algo-psc-diet-v5.en.laikang.com
test:
  langchain: http://10.228.67.99:26924
  llm: http://localhost:50013
  llm_token: sk-laikang-aihealthmanager-test
  graph: http://10.4.164.240:26925
  ai_backend: https://gate-dev.op.laikang.com/aihealthmanager-dev
  algo_rec: http://aimp-algo-psc-diet-v5.ef.laikang.com
fat:
  langchain: http://10.228.67.99:26924
  llm: http://localhost:50013
  llm_token: sk-laikang-aihealthmanager-fat
  graph: http://10.4.164.240:26925
  ai_backend: https://gate-qa.op.laikang.com/aihealthmanager-qa
  algo_rec: http://aimp-algo-psc-diet-v5.eo.laikang.com