local:
    graph: http://10.4.164.240:26925
    ai_backend: https://gate-dev.op.laikang.com/aihealthmanager-dev
    algo_rec: http://aimp-algo-psc-diet-v5.en.laikang.com
    langchain: http://10.228.67.99:26924
    model_supply:
        default: vllm
        vllm:
            api_base: http://10.39.91.251:40024
            api_key: sk-QZqVzsbLfql5texCBb27C4958e2b412798F2Ba0e34D958C5
            support_models:
            - Baichuan2-7B-Chat
            - Qwen2-7B-Instruct
            - Qwen-14B-Chat
            - Qwen1.5-14B-Chat
            - Qwen1.5-32B-Chat
            - Qwen1.5-72B-Chat
            - Qwen2-72B-Instruct
            - bce-embedding-base-v1
            - Qwen-VL-base-0.0.1
dev:
    graph: http://10.4.164.240:26925
    ai_backend: https://gate-dev.op.laikang.com/aihealthmanager-dev
    algo_rec: http://aimp-algo-psc-diet-v5.en.laikang.com
    langchain: http://10.228.67.99:26924
    model_supply:
        default: vllm
        vllm:
            api_base: http://172.27.9.34:26928
            api_key: sk-OpGo5utOhkj46N6Z3fCeFd8792Cd4a939b029b9b18951344
            support_models:
                - Baichuan2-7B-Chat
                - Qwen2-7B-Instruct
                - Qwen-14B-Chat
                - Qwen1.5-14B-Chat
                - Qwen1.5-32B-Chat
                - Qwen1.5-72B-Chat
                - Qwen2-72B-Instruct
                - bce-embedding-base-v1
                - Qwen-VL-base-0.0.1
prod:
    graph: http://10.4.164.240:26925
    ai_backend: https://gate.op.laikang.com/aihealthmanager
    algo_rec: http://aimp-algo-psc-diet-v5.en.laikang.com
    langchain: http://10.228.67.99:26924
    model_supply:
        default: vllm
        vllm:
            api_base: http://172.27.18.60:26928
            api_key: sk-Wy62RaRYU0JXptKG79DaD45aB3C845F3A0959bBd92AeB907
            support_models:
                - Baichuan2-7B-Chat
                - Qwen2-7B-Instruct
                - Qwen-14B-Chat
                - Qwen1.5-14B-Chat
                - Qwen1.5-32B-Chat
                - Qwen1.5-72B-Chat
                - Qwen2-72B-Instruct
                - bce-embedding-base-v1
                - Qwen-VL-base-0.0.1
