local:
  langchain: http://10.228.67.99:26924
  llm: http://10.228.67.99:26921
  graph: http://10.4.164.240:26925
  ai_backend: https://gate-dev.op.laikang.com/aihealthmanager-dev
dev:
  langchain: http://10.228.67.99:26924
  llm: http://10.228.67.99:26921
  graph: http://10.4.164.240:26925
  ai_backend: https://gate-dev.op.laikang.com/aihealthmanager-dev
fat:
  langchain: http://10.228.67.99:26924
  llm: http://10.228.67.99:26925
  graph: http://10.4.164.240:26925
  ai_backend: https://gate-dev.op.laikang.com/aihealthmanager-dev
prod:
  langchain: http://10.228.67.99:26924
  llm: http://10.228.67.99:26925
  graph: http://10.4.164.240:26925
  ai_backend: https://gate-dev.op.laikang.com/aihealthmanager-dev