local:
  LANGFUSE_SECRET_KEY: sk-lf-dd72d122-597f-4816-be79-605ecdabc575
  LANGFUSE_PUBLIC_KEY: pk-lf-006f983d-9437-4d7b-8b01-b17b03a5ab91
  LANGFUSE_HOST: https://ai-health-manager-langfuse-web.op.laikang.com

dev:
  LANGFUSE_SECRET_KEY: sk-lf-a5e9f748-c8e7-4ff3-807b-f6e89baea0af
  LANGFUSE_PUBLIC_KEY: pk-lf-39c714d8-d6ea-45f6-b538-e4290ba53206
  LANGFUSE_HOST: https://ai-health-manager-langfuse-web.op.laikang.com

prod:
  LANGFUSE_SECRET_KEY: sk-lf-dd72d122-597f-4816-be79-605ecdabc575
  LANGFUSE_PUBLIC_KEY: pk-lf-006f983d-9437-4d7b-8b01-b17b03a5ab91
  LANGFUSE_HOST: https://ai-health-manager-langfuse-web.op.laikang.com