local:
  ip: 10.39.10.28
  port: 3306
  user: root
  passwd: "12345678"
  db_name: ai_health_manager_db
dev:
  ip: 10.39.10.28
  port: 3306
  user: root
  passwd: "12345678"
  db_name: ai_health_manager_db
test:
  ip: pc-2ze23ih17gujd950v.mysql.polardb.rds.aliyuncs.com
  port: 3306
  user: lk_base_n_qa
  passwd: fpBase09@23aQdn
  db_name: lk-h-aihealthmanager-qa
fat:
  ip: pc-2ze23ih17gujd950v.mysql.polardb.rds.aliyuncs.com
  port: 3306
  user: lk_base_n_qa
  passwd: fpBase09@23aQdn
  db_name: lk-h-aihealthmanager-qa