local:
  ip: 10.39.10.28
  port: 3306
  user: root
  passwd: "12345678"
  db_name: ai_health_manager_db
dev:
  ip: 10.39.10.28
  port: 3306
  user: root
  passwd: "12345678"
  db_name: ai_health_manager_db
fat:
  ip: 10.39.10.28
  port: 3306
  user: root
  passwd: "12345678"
  db_name: ai_health_manager_db