POST /chat/complete HTTP/1.1
Content-Type: application/json
Host: 0.0.0.0:6500


{
    "orgCode": "sf",
    "customId": "30",
    "prompt": "你作为家庭智能健康管家，需要解答用户问题，如果用户回复了症状，则针对用户症状进行问诊；当用户提到高血压的相关症状时，如果对话历史中没有血压信息，则提示用户测量血压，如果对话中问过血压信息，就不要再问了，如果对话历史里有血压信息，则针对用户高血压症状问诊；如果用户提到其他疾病症状则对用户症状进行问诊。如果模型回复饮食情况则对用户饮食进行热量、膳食结构评价。今天日期是${currentDate}。用户个人信息如下：\\n您好，今天天气晴朗，气温适宜，出门记得带伞哦！['男性']\n\n问题：您的性别？ 回答：['婴幼儿':≤5岁, '儿童':6-1185.8cm\n\n问题：请问您的身高是多50kg_____\n\n体力劳动强度中_____\n\n有基础疾病{'糖尿病家族史': True, '冠心好的，那我们就从您的目标出发，制定一个健康计划。\n\n根据您的身高、体重、年龄和生活习惯，您的BMI为喜咸，喜辣，喜甜\n\n标签值为：喜咸，喜辣不喜欢吃甜的对话内容为：",
    "intentCode": "other",
    "history": [
        {
            "msgId": "9522272901",
            "role": "1",
            "content": "我最近好像得了甲流身体疼痛，呃，那个发烧高烧后疼痛，我该怎么办？",
            "sendTime": "2023-12-13 09:30:33"
        },
        {
            "msgId": "5761639987",
            "role": "3",
            "content": "请问您的症状持续了多久？是突然出现的吗？有什么诱因吗？疼痛发生在哪个部位？",
            "sendTime": "2023-12-13 09:30:42"
        },
        {
            "msgId": "3046933509",
            "role": "1",
            "content": "是突然出现的。",
            "sendTime": "2023-12-13 09:31:03"
        },
        {
            "msgId": "7294833196",
            "role": "3",
            "content": "请问您的疼痛部位在哪里？持续了多久？",
            "sendTime": "2023-12-13 09:31:17"
        },
        {
            "msgId": "1752779781",
            "role": "1",
            "content": "疼痛的话是浑身疼痛如芒刺背。",
            "sendTime": "2023-12-13 09:31:17"
        }
    ],
    "backend_history": [],
    "promptParam": {
        "askName": "用户叫您好，今天天气晴朗，气温适宜，出门记得带伞哦！,",
        "askAge": "用户出生日期是['婴幼儿':≤5岁, '儿童':6-1,",
        "askSix": "用户性别是['男性']\n\n问题：您的性别？ 回答：,",
        "askNation": "",
        "askWeight": "用户体重是50kg,",
        "askHeight": "用户身高是185.8cm\n\n问题：请问您的身高是多,",
        "askLaborIntensity": "用户体力劳动强度是_____\n\n体力劳动强度中,",
        "askDisease": "用户现在患疾病有_____\n\n有基础疾病,",
        "askFamilyHistory": "用户家族病史有{'糖尿病家族史': True, '冠心,",
        "askGoalManage": "用户健康目标是好的，那我们就从您的目标出发，制定一个健康计划。\n\n根据您的身高、体重、年龄和生活习惯，您的BMI为,",
        "askTastePrefer": "用户饮食口味是喜咸，喜辣，喜甜\n\n标签值为：喜咸，喜辣,",
        "askFoodAlergy": "用户过敏食物是不喜欢吃甜的,",
        "askMmolDrug": "",
        "askExerciseHabbit": "",
        "askExerciseTabooDegree": "",
        "askExerciseTabooXt": "",
        "currentDate": "2023年12月13日"
    }
}

# {
#     "msgId": "5985801019",
#     "role": "3",
#     "content": "Thought: 该回答问题了Observation: 您的症状可能是甲流引起的全身疼痛，建议您尽快去医院就诊，同时注意休息，多喝水，避免过度劳累。如果疼痛加重或出现其他症状，如呼吸困难、胸痛等，请立即就医。Thought: 我会作答了Observation: 您的症状可能是甲流引起的全身疼痛，建议您尽快去医院就诊，同时注意休息，多喝水，避免过度劳累。如果疼痛加重或出现其他症状，如呼吸困难、胸痛等，请立即就医。Thought: 我会作答了Observation: 您的症状可能是甲流引起的全身疼痛，建议您尽快去医院就诊，同时注意休息，多喝水，避免过度劳累。如果疼痛加重或出现其他症状，如呼吸困难、胸痛等，请立即就医。Thought: 该回答问题了Observation: 您的症状可能是甲流引起的全身疼痛，建议您尽快去医院就诊，",
#     "sendTime": "2023-12-13 09:31:36"
# },
# {
#     "msgId": "7262789311",
#     "role": "1",
#     "content": "你说的这些问题怎么乱七八糟的，我到底该怎么办呀？我就想问一下你。",
#     "sendTime": "2023-12-13 09:37:22"
# }

# {
#     "orgCode": "sf", 
#     "customId": "007", 
#     "prompt": "你将扮演一个AI营养师助手，帮助真人营养师为健康或慢病用户出具营养处方，使用askAPI工具帮助用户做出三济饮食处方的推荐。", 
#     "qprompt": "", 
#     "tool_in_use": [
#         "调用接口", 
#         "询问用户", 
#         "话题完成", 
#         "话题终结"
#         ], 
#     "intentCode": "auxiliary_diagnosis", 
#     "history": [
#         {"msgId": "9945430515", "role": "1", "content": "帮我推荐今天吃啥", "sendTime": "2023-12-06 17:29:58"}
#     ], 
#     "promptParam": {"currentDate": "2023年12月06日", "askExerciseTabooXt": "", "askSix": "", "askExerciseHabbit": "", "askName": "", "askFamilyHistory": "", "askGoalManage": "", "askMmolDrug": "", "askFoodAlergy": "", "askAge": "", "askDisease": "", "askHeight": "", "askExerciseTabooDegree": "", "askLaborIntensity": "", "askNation": "", "askWeight": "", "askTastePrefer": ""}, "backend_history": []
# }


# 1.首先使用工具searchDB，查询用户标签，获得：年龄、身高、体重、性别、体重状态、现患疾病、口味偏好、饮食习惯、民族、营养管理目标、口味偏好-能否吃辣\n
# 2.如果没有查询到上述信息，你需要使用工具askHuman，询问用户得知上述信息。\n
# 3.根据上面已经得知的信息，使用工具askAPI，调用三济饮食处方接口，获得该用户的推荐摄入热量值。\n
# 4.使用工具searchKB，查询知识，获得符合用户画像的饮食原则、食谱计算方法\n
# 5.使用工具searchDB，查询食谱和食材的营养数据，结合上面获得的饮食原则、食谱计算方法、推荐摄入热量、用户画像标签等信息为用户出具一日食谱\n
# 6.食谱应该包含早、中、晚正餐，以及加餐的时间指导、推荐的食物、推荐食物的质量指导，部分食物尽量将质量换算成常见的单位数量，例如200克苹果换算成1个苹果。\n
# 7.输出结果格式为：\n早餐：时间\n食物名称：食物质量或常见质量单位\n上午加餐：时间\n食物名称：食物质量或常见质量单位\n午餐：时间\n食物名称：食物质量或常见质量单位\n下午加餐：时间\n食物名称：食物质量或常见质量单位\n晚餐：时间\n食物名称：食物质量或常见质量单位\n晚上加餐：时间\n食物名称：食物质量或常见质量单位\n
# 8.输出举例：\n早餐：6：30-8：30\n全麦面包2片，鸡蛋1个，苹果1个，牛奶200ml\n午餐：11：30-12：30\n杂粮饭200g，西红柿炒鸡蛋150g，炒油麦菜100g\n下午加餐：15：00\n坚果10g\n晚餐：18：00-19：00\n小米粥150g，水煮虾50g，凉拌黄瓜100g\n