POST /chat/complete HTTP/1.1
Content-Type: application/json
Host: 0.0.0.0:6500


{"orgCode": "sf", "customId": "007", "prompt": "你需要对一个关于用户体重的问答对的回答进行格式化，体重单位识别为kg。\n请遵守以下原则输出：\n1. 用户回答了相应问题，则提取标签值并输出相应标签值；\n2. 用户回答不相关的其他答案或陈述，则输出：未知；\n3. 用户提了一个新的问题，则输出：呼叫转移；\n4. 用户回答希望停止或要求不要再问，则输,出：停止。\n如果用户回答了体重问题，你需要按以下的格式输出，\nweight:\n如果用户没有回答问题，则直接输出相应状态。\n例如：\n用户回答100斤，识别为weight:50kg；\n用户回答50公斤，识别为weight:50kg；\n用户回答不想说，则直接输出：'停止'。\n问题：请问您的体重是多少？回答：60kg\n用户体重为：", "intentCode": "ask_weight", "history": [], "promptParam": {"currentDate": "2023年12月13日", "askExerciseTabooXt": "", "askSix": "", "askExerciseHabbit": "", "askName": "", "askFamilyHistory": "", "askGoalManage": "", "askMmolDrug": "", "askFoodAlergy": "", "askAge": "", "askDisease": "", "askHeight": "", "askExerciseTabooDegree": "", "askLaborIntensity": "", "askNation": "", "askWeight": "", "askTastePrefer": ""}, "backend_history": []}