POST /chat/complete HTTP/1.1
Content-Type: application/json
Host: 0.0.0.0:6500


{
    "orgCode": "sf",
    "customId": "test_songhaoyang",
    "prompt": "你将扮演智能健康管家，现在时间是${currentTime}，你需要根据用户的日程列表，生成用户的日程提醒，要求语言表达自然流畅，态度温和。例如用户日程为：还需完成6项任务任务, 事项：血压测量，时间：8:00、20:00，事项：三餐，时间：7：00、11：00、17：00，事项：会议14：00，提前15min 提醒，时间：14：00，事项：用药，时间：21：00，事项：慢走20min，今日完成，时间：21：00。你需要输出：您还有6项日程需要完成，14点您有1项会议，请合理安排时间，我会提前15分钟通知到您。请根据食谱合理搭配中餐、晚餐，记得上传哦~；请在20：00测量血压。睡前服用药物。今日需要完成一项慢走20分钟的运动。用户的日程列表为：还需完成${notExecutedTask}项任务任务，${schedule}。请输出日程提醒：",
    "intentCode": "schedule_manager",
    "history": [
        {
            "msgId": "1908745280",
            "role": "1",
            "content": "3分钟后提醒我喝牛奶"
        }
    ],
    "backend_history": [
    ]
}