POST /component_list HTTP/1.1
Content-Type: application/json
Host: aimp-algo-psc-diet-v5.en.laikang.com

{
    "baseInfoExtra": {
        "height": 173,
        "weight": 65
    },
    "baseInfoList": {
        "age": "20",
        "physicalActivity": "轻",
        "physiologicalStage": "",
        "religiousBelief": "汉族",
        "sex": "女"
    },
    "limitRecipesNums": 6,
    "is_common":"1"
}




# "dietHabbit": {
#     "dietaryPattern": [
#         "忌鸡蛋"
#     ]
# },
# "diseaseList": ["糖尿病","肥胖","脂肪肝"],
# "domain": {
#     "org": "7",
#     "rcls":"1",
#     "r_dsids": ["825", "842", "245", "207"],
#     "r_names":["豉油鸡","双色包菜","低脂牛奶","茯苓山药粥", "YS有机花菜/宴会"],
#     "r_codes":["lk1651974552682","lk1651974551947","lk1651974550430"]
# },
# "supply": [
#     "中餐"
# ]